version: 0.0
os: linux
files:
  - source: /fundoo/fundooapp/templates/index.html
    destination: /var/www/html/
hooks:
  BeforeBlockTraffic:
    - location: scripts/beforeBlockTraffic.sh
      timeout: 300
      runas: root
  AfterBlockTraffic:    
    - location: scripts/afterBlockTraffic.sh
      timeout: 300
      runas: root  
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root      
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 300
      runas: root      
  ApplicationStart:  
    - location: scripts/start.sh
      timeout: 300
      runas: root           
  BeforeAllowTraffic:
    - location: scripts/beforeAllowTraffic.sh
      timeout: 300
      runas: root
  AfterAllowTraffic:
    - location: scripts/afterAllowTraffic.sh
      timeout: 300
      runas: root
